#see https://github.com/pre-commit/action#using-this-action-in-private-repositories
name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
