name: test-deploy-script
on:
    pull_request:
    push:

jobs:
  test-ssh:
    runs-on: self-hosted
    environment: no-secret
    steps:
    #   - name: Deploy code
    #     uses: easingthemes/ssh-deploy@main
      - name: Start Odoo 
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: $LOCAL_DEPLOY_HOST
            username: $LOCAL_SSH_USER
            key: $LOCAL_PRIVATE_SSH_KEY
            port: $LOCAL_SSH_PORT
            script: |
                echo "Hello world!"
                id
                touch a
                echo "${{ secrets.SSH_PORT }}"
