name: test-deploy-script
on:
    pull_request:
    push:

jobs:
  test-ssh:
    runs-on: self-hosted
    environment: no-secret
    steps:
    #   - name: Deploy code
    #     uses: easingthemes/ssh-deploy@main
      - name: Start Odoo 
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ vars.LOCAL_DEPLOY_HOST }}
            username: ${{ vars.LOCAL_SSH_USER }}
            key: ${{ vars.LOCAL_PRIVATE_SSH_KEY }}
            port: ${{ vars.LOCAL_SSH_PORT }}
            script: |
                echo "Hello world!"
                id
                touch a
                echo "TTT"
