name: test-deploy-script
on:
    pull_request:
    push:

jobs:
  test-ssh:
    runs-on: self-hosted
    steps:
    #   - name: Deploy code
    #     uses: easingthemes/ssh-deploy@main
      - name: Start Odoo 
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            port: ${{ secrets.SSH_PORT }}
            key: ${{ secrets.PRIVATE_SSH_KEY }}
            script: |
                echo "Hello world!"
                id
                touch a
